name: golang tests
on:
  push:
    branches:
      - main
    paths:
      - "!.github/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./some-golang-code
    steps:
    - name: Bring in the code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
    - name: Get dependencies
      run: go get .
    - name: Run tests
      run: go test -v