name: golang tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./some-golang-code
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'
    - name: Get dependencies
      run: |
        echo "current folder: $(pwd)" && go get .
    - name: Run tests
      run: go test -v