name: golang releaser
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "!.github/**"
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        goos: [linux, windows]
        goarch: [amd64, 386, arm64]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./some-golang-code
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Build
        run: go build -o "${{ github.workspace }}/greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}" main.go
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

      # - name: Archive
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
      #     path: ${{ github.workspace }}/greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
      #     retention-days: 1
  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
  #         path: ${{ github.workspace }}
  #     - name: Publish to GitHub Releases
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: ${{ github.workspace }}/greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
