name: golang releaser
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "!.github/**"
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        goos: [linux, windows]
        goarch: [amd64, 386, arm64]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./some-golang-code
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Build
        run: go build -o "greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}" main.go
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: greeter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
          path: /some-golang-code/greeter-$GOOS-$GOARCH${{ matrix.goos == 'windows' && '.exe' || '' }}
